# Uncomment the next line to define a global platform for your project
 #platform :ios, '9.0'

target 'Card Factory Challenage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Card Factory Challenage

  #pod 'Alamofire', '5.0.0-beta.3'
   pod 'AFNetworking', '~> 3.0'
  target 'Card Factory ChallenageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
